apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: pkarugu/eureka-server:latest
          ports:
            - containerPort: 8055
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_ZIPKIN_SENDER_TYPE
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: SPRING_ZIPKIN_SENDER_TYPE
            - name: SPRING_ZIPKIN_RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: RABBIT_QUEUE
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: SPRING_RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: SPRING_RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: RABBIT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: RABBIT_PASSWORD
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: banking-configmap
                  key: SPRING_CONFIG_IMPORT

---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8055
      targetPort: 8055